### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [MrEvilGamer/qb-tattooshop#22]
Just added the script and and launched the sql. Still get some kind of error
![image](https://user-images.githubusercontent.com/94759971/190677590-77ec2215-a56b-4eae-a500-b388f4d9feb6.png)

**Comment by xxUnknown13xx** [comment]
same here man..
![tattoo error](https://user-images.githubusercontent.com/113321753/192494447-2acf9ebd-a243-4b9f-977f-b1c6761d9b75.PNG)

**Comment by JohnSacadorian1** [comment]
> same here man.. ![tattoo error](https://user-images.githubusercontent.com/113321753/192494447-2acf9ebd-a243-4b9f-977f-b1c6761d9b75.PNG)

Add this to the top of the file which you are getting the error from. "local QBCore = exports['qb-core']:GetCoreObject()"

**Comment by xxUnknown13xx** [comment]
> > same here man.. ![tattoo error](https://user-images.githubusercontent.com/113321753/192494447-2acf9ebd-a243-4b9f-977f-b1c6761d9b75.PNG)
> 
> Add this to the top of the file which you are getting the error from. "local QBCore = exports['qb-core']:GetCoreObject()"

It's already in it :/

**Comment by MrEvilGamer** [comment]
Hey Guys thank you for reporting, can you guys try now i have updated the script

**Comment by xxUnknown13xx** [comment]
> Hey Guys thank you for reporting, can you guys try now i have updated the script

It works for now :) Thank you for fixing it

** can i delete this thread without effecting the script?**

CreateThread(function()
    while true do
        Wait(0)
        
        for i = 1, #Config.Shops, 1 do
            local player = PlayerPedId()
            local playerloc = GetEntityCoords(player, 0)
            local coordinates = Config.Shops[i]
            local dist = GetDistanceBetweenCoords(coordinates['x'], coordinates['y'], coordinates['z'], playerloc['x'], playerloc['y'], playerloc['z'], true)
            if dist <= 8 then
                DrawText3Ds(coordinates.x, coordinates.y, coordinates.z + 0.10, "/removealltattoo to remove all tattoos.")
            end
        end
    end
end)

**Comment by ghost** [comment]
Still get this error
![image](https://user-images.githubusercontent.com/94759971/193443197-d77f04ef-5a68-4954-b573-8807b6f85863.png)

**Comment by MrEvilGamer** [comment]
not sure how you guys are even managing to get that error can you please elaborate?

**Comment by gigitygamer** [comment]
Hello I am getting the same error above, everything is working but it just prints this error every once in a while

![image](https://user-images.githubusercontent.com/118565851/205777928-3a8f51f2-4a8e-4e79-863b-896bf940c790.png)

**Comment by gigitygamer** [comment]
![image](https://user-images.githubusercontent.com/118565851/206871294-5d0e6a22-5c89-472e-b0eb-997af6b949ae.png)

**Comment by SGH-Scripts** [comment]
I am also getting this error

**Comment by xxUnknown13xx** [comment]
Since the update when i had an issue, everything been fine for me. odd how theyre all getting errors..

**Comment by SGH-Scripts** [comment]
Issue was that in the database, a character had a value of 0 in the tattoo data table

**Comment by MrEvilGamer** [comment]
so that was the fix i think? thanks DrifterTV :)

**Comment by gigitygamer** [comment]
![image](https://user-images.githubusercontent.com/118565851/207959957-405068b8-b3dc-4732-bf7f-e5b5b7207c32.png)

Was not the root of my issue
